//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelloWorldBot.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HelloWorldBot.Resources.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want me to check in with you on weekends too?.
        /// </summary>
        public static string AskIfCheckInWeekend {
            get {
                return ResourceManager.GetString("AskIfCheckInWeekend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awesome! The journey will require discipline and your commitment to improve your life.  I’ll assume you read everything and do everything in order to succeed. Let’s do this!  
        ///
        ///What is a good time to check in with you each day?.
        /// </summary>
        public static string AskTimeForCheckin {
            get {
                return ResourceManager.GetString("AskTimeForCheckin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi {0},
        ///
        ///We are all given just 24hrs a day. Some of us achieve great things and others very little. What are you doing with your time?
        ///
        ///I am here to guide you each day in the journey to mastering your relationship with time ⏳, focus 🎯 and productivity ☕.
        ///
        ///To get started, I’ll check in with you during your workday to see what you’re working on. I’ll keep track of your time, how you spend your hours and make suggestions of when to take breaks 🔋.
        ///
        ///At the end of the day I’ll give you a report 📊 of ho [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AskToJoinLetter {
            get {
                return ResourceManager.GetString("AskToJoinLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both saturday and sunday.
        /// </summary>
        public static string BothSaturdaySunday {
            get {
                return ResourceManager.GetString("BothSaturdaySunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8:00.
        /// </summary>
        public static string EightHour {
            get {
                return ResourceManager.GetString("EightHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8:30.
        /// </summary>
        public static string HalfPastEight {
            get {
                return ResourceManager.GetString("HalfPastEight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I’ll check in with you each workday at {0}.
        /// </summary>
        public static string InformCheckIntime {
            get {
                return ResourceManager.GetString("InformCheckIntime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9:00.
        /// </summary>
        public static string NineHour {
            get {
                return ResourceManager.GetString("NineHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No I am not interested improving my life.
        /// </summary>
        public static string NoIamNotInterestedImprovingMyLife {
            get {
                return ResourceManager.GetString("NoIamNotInterestedImprovingMyLife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok, noted Let’s get started!.
        /// </summary>
        public static string OkNoted {
            get {
                return ResourceManager.GetString("OkNoted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hmm… sorry to hear that. Thanks for stopping by.
        /// </summary>
        public static string SorryForNotBeingOnBoard {
            get {
                return ResourceManager.GetString("SorryForNotBeingOnBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10:00.
        /// </summary>
        public static string TenHour {
            get {
                return ResourceManager.GetString("TenHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, bring it on!.
        /// </summary>
        public static string YesBringItOn {
            get {
                return ResourceManager.GetString("YesBringItOn", resourceCulture);
            }
        }
    }
}
